### ISSUE TITLE
This Windows version (6.3.9600) does not support the required bluetooth API.

### ISSUE THREAD

**Issue by IreneCrisologo** [GIS4WRF/gis4wrf#103]
**Describe the bug**
An error window appears, saying "This Windows version (6.3.9600) does not support the required bluetooth API. Consider updating to a more recent Windows (10.0.10685 or above)."

**To Reproduce**
I installed the latest QGIS (3.4, 64-bit). In the Plugins > Manage and Install Plugins menu I searched for GIS4WRF and clicked on "Install plugin". Then the error appeared.

**Expected behavior**
I expected that the plugin would be installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4422950/49081515-67a0ee80-f247-11e8-8a3e-99952e3b8e31.png)

**Operating System Information (please complete the following information):**
 - OS: Windows 8.1 Pro

**Comment by letmaik** [comment]
Thanks for reporting this. It seems to be an issue with a dependency (PyQT) of QGIS that's not working on older Windows versions in all cases. See also https://github.com/enricofer/go2streetview/issues/41, or https://github.com/winpython/winpython/issues/592. There seems to exist a weird work-around but ultimately this should be fixed in QGIS or that dependency. If there are more reports from users with this issue we may decide to implement the work-around, but for now this has low priority. I would recommend updating to Windows 10, or alternatively opening an issue in the QGIS bug tracker. If you decide to do the latter, please add the link in here for reference.

**Comment by dmey** [comment]
Closing. @IreneCrisologo please let us know if this is still an issue.

**Comment by Fabien98** [comment]
Hello,
I just opened an issue in the QGIS bugtracker as recommended:
https://issues.qgis.org/issues/20867

**Comment by qmor** [comment]
I've "solve" this on my PC:

Go to c:\Python37\Lib\site-packages\PyQt5\Qt\bin\ (or where your python installed in) and rename 

Qt5Bluetooth.dll to Qt5Bluetooth.dll1
