### ISSUE TITLE
SyntaxError loading GIS4WRF

### ISSUE THREAD

**Issue by wcarthur** [GIS4WRF/gis4wrf#130]
**Describe the bug**
GIS4WRF plugin fails to load due to error in the classFactory() method. This is linked to a `SyntaxError` in `gis4wrf/plugin/ui/helpers.py` (line 280) - see below for output when loading the plugin.

> SyntaxError: invalid syntax 
> Traceback (most recent call last):
>   File "/apps/qgis/3.4.5-py3.5/share/qgis/python/qgis/utils.py", line 335, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/547/cxa547/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
>     bootstrap_with_ui(iface)
>   File "/home/547/cxa547/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 31, in bootstrap_with_ui
>     from gis4wrf.plugin.ui.helpers import WaitDialog
>   File "/apps/qgis/3.4.5-py3.5/share/qgis/python/qgis/utils.py", line 672, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/547/cxa547/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/helpers.py", line 280
>     f'{e}. Interested in making GIS4WRF better? ' +
>                                                       ^
> SyntaxError: invalid syntax
> 
> 
> Python version: 3.5.2 (default, Jun 29 2016, 14:55:45) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] 
> QGIS version: 3.4.5-Madeira Madeira, exported

**Comment by dmey** [comment]
Thanks for reporting this issue but I am afraid we do not explicitly support your platform. For a list of supported platforms see: https://gis4wrf.github.io/installation/#supported-platforms. The error you see happens because you are using a version of Python which does not support [formatted string literals](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals) (< 3.6 ) which we make use in our code and decided against adding support for Python 3.5 for [these reasons](https://github.com/GIS4WRF/gis4wrf/issues/16#issuecomment-401564951). You may still be able to get GIS4WRF running on your system if you upgrade to Python 3.6.

**Comment by wcarthur** [comment]
Not a problem - I'll follow up with our admins. Thought it might be as simple as that...
