### ISSUE TITLE
Bug: AssertionError when writing to Geogrid Binary Format

### ISSUE THREAD

**Issue by ianbtr** [GIS4WRF/gis4wrf#135]
**Description**
An AssertionError is displayed when attempting to convert the current layer to a WPS binary using the "Convert active layer to WPS binary" button/wizard.

**To Reproduce**
1. Open any netcdf-3 file with non-categorical data as a layer. My file has the variables "lat_bnds", "lon_bnds" and a non-categorical quantity stored in it.
2. With no other layers selected, click the "Convert active layer to WPS binary" button.
3. Select "No" when prompted with "Is this layer's data categorical?"
4. Select an empty directory from the file browser.

**Expected behavior**
A geogrid binary format file should have been produced in the selected empty directory, along with an index file.

**Screenshots**
![image](https://user-images.githubusercontent.com/32246517/57571950-7f79c280-73e2-11e9-8ff4-ca8569b79c3c.png)

**Operating System Information (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I will try with a single-variable and/or netcdf-4 file next. Really hoping that works.

**Comment by letmaik** [comment]
Thanks for the report. Would you be able to share a file which has that problem? If it's not too big you can attach it directly here.

**Comment by ianbtr** [comment]
It'll take me a few minutes to de-identify the data, but I'll have one for
you momentarily.

Ian Bertram

**Comment by ianbtr** [comment]
There we go.

Ian Bertram

**Comment by letmaik** [comment]
@ianbtr I guess GitHub doesn't automatically attach email attachments. You probably have to use the web UI for that.

**Comment by ianbtr** [comment]
[data.zip](https://github.com/GIS4WRF/gis4wrf/files/3169267/data.zip)

Apparently the web interface doesn't like netcdf files.

**Comment by letmaik** [comment]
I could reproduce the issue and created a fix (#136). Please read the PR text for details. A quick way to work-around the issue without waiting for the next gis4wrf version is to simply re-save the layer from QGIS into a new GeoTIFF or NetCDF file (right-click on layer -> Export). This creates a file which doesn't lack CRS metadata and also doesn't trigger the assertion you reported.

Note that your layer data type is float and gis4wrf automatically encodes this into scale/offset integer format as this is what WPS Binary requires. In your particular case it chooses 64-bit floats (by estimating significant digits in the input data). This is all fine, but be aware that 64-bit WPS Binary datasets currently cannot be opened again in gis4wrf for visualization due to limitations in the underlying libraries (GDAL only supports up to 32-bit).

**Comment by ianbtr** [comment]
Thank you :+1 your help is very much appreciated.
