### ISSUE TITLE
Latitude and longitude are opposite in center point of Domain Configuration for Lambert projection

### ISSUE THREAD

**Issue by bakamotokatas** [GIS4WRF/gis4wrf#152]
**Describe the bug**
In Simulation -> Domain -> Center Point
latitude and longitude are set wrongly. They are set opposite.

When you enter latitude to latitude box, its shows it in map as longitude. And when you enter longitude to longitude box, its shows it in map as latitude. You can look in screenshot.

**Expected behavior**
When you enter latitude to latitude, it should show correct location in map. Also in longitude.
 
**Screenshots**
![gis4wrf_bug](https://user-images.githubusercontent.com/22841746/70832467-3b322300-1e06-11ea-9d5e-e873f84acfce.png)

**Operating System Information (please complete the following information):**
 - OS: Manjaro(Linux)
 - 18.1.3

**Comment by letmaik** [comment]
I can confirm this for Lambert. It doesn't happen when using the Lat/Lon GCS. Since this worked fine in the past there must have been some change in QGIS or its dependencies GDAL or PROJ.

Which QGIS version are you using? Can you also check which GDAL and PROJ versions QGIS uses? See Help -> About.
