### ISSUE TITLE
Error in adding/installing gis4wrf on Windows

### ISSUE THREAD

**Issue by neluwala** [GIS4WRF/gis4wrf#153]
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\neluw\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\neluw\AppData\Local\gis4wrf\python37I:\programs\qgis\bin\python-qgis.bat -m pip install --prefix C:\Users\neluw\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2   Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz Collecting netCDF4==1.4.2   Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl Collecting wrf-python==1.3.2   ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl   ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl 
Traceback (most recent call last):
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['I:\\programs\\qgis\\bin\\python-qgis.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\neluw\\AppData\\Local\\gis4wrf\\python37', 'f90nml==1.0.2', 'netCDF4==1.4.2', 'https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:/programs/qgis/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\neluw\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\neluw\AppData\Local\gis4wrf\python37I:\programs\qgis\bin\python-qgis.bat -m pip install --prefix C:\Users\neluw\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2
  Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz
Collecting netCDF4==1.4.2
  Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl
Collecting wrf-python==1.3.2
  ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl
  ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r
ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python Path:
I:/programs/qgis/apps/qgis/./python
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
I:/programs/qgis/apps/qgis/./python/plugins
I:\programs\qgis\bin\python37.zip
I:\programs\qgis\apps\Python37\DLLs
I:\programs\qgis\apps\Python37\lib
I:\programs\qgis\bin
I:\programs\qgis\apps\Python37
I:\programs\qgis\apps\Python37\lib\site-packages
I:\programs\qgis\apps\Python37\lib\site-packages\win32
I:\programs\qgis\apps\Python37\lib\site-packages\win32\lib
I:\programs\qgis\apps\Python37\lib\site-packages\Pythonwin
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\neluw\AppData\Local\gis4wrf\python37
C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packagesCouldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\neluw\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\neluw\AppData\Local\gis4wrf\python37I:\programs\qgis\bin\python-qgis.bat -m pip install --prefix C:\Users\neluw\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2   Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz Collecting netCDF4==1.4.2   Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl Collecting wrf-python==1.3.2   ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl   ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl 
Traceback (most recent call last):
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['I:\\programs\\qgis\\bin\\python-qgis.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\neluw\\AppData\\Local\\gis4wrf\\python37', 'f90nml==1.0.2', 'netCDF4==1.4.2', 'https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:/programs/qgis/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\neluw\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\neluw\AppData\Local\gis4wrf\python37I:\programs\qgis\bin\python-qgis.bat -m pip install --prefix C:\Users\neluw\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2
  Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz
Collecting netCDF4==1.4.2
  Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl
Collecting wrf-python==1.3.2
  ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl
  ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r
ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=PZI%2Fiw8DAwOh8aWkzrTCrAlaDg%2Fm3fziWlX%2Bwtv%2B51s%3D&st=2019-12-14T11%3A19%3A12Z&se=2019-12-14T11%3A25%3A12Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python Path:
I:/programs/qgis/apps/qgis/./python
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
I:/programs/qgis/apps/qgis/./python/plugins
I:\programs\qgis\bin\python37.zip
I:\programs\qgis\apps\Python37\DLLs
I:\programs\qgis\apps\Python37\lib
I:\programs\qgis\bin
I:\programs\qgis\apps\Python37
I:\programs\qgis\apps\Python37\lib\site-packages
I:\programs\qgis\apps\Python37\lib\site-packages\win32
I:\programs\qgis\apps\Python37\lib\site-packages\win32\lib
I:\programs\qgis\apps\Python37\lib\site-packages\Pythonwin
C:/Users/neluw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\neluw\AppData\Local\gis4wrf\python37
C:\Users\neluw\AppData\Local\gis4wrf\python37\lib\site-packages

**To Reproduce**
Go to plugin
add qgis4wrf plugin

**Expected behavior**
plugin installation and stopp with this error 

**Screenshots**

**Operating System Information (please complete the following information):**
windows 10

![1](https://user-images.githubusercontent.com/10020525/70848075-63fffa00-1e92-11ea-9bf3-4fb9a990ccb0.PNG)
![2](https://user-images.githubusercontent.com/10020525/70848076-63fffa00-1e92-11ea-83b8-5387aeca1c83.PNG)

**Comment by nbusired** [comment]
I am also facing the same error during installation. Is there any way to resolve this issue?


Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\bnkre\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\bnkre\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\bnkre\AppData\Local\gis4wrf\python37C:\Program Files\QGIS 3.4\bin\python-qgis-ltr.bat -m pip install --prefix C:\Users\bnkre\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2   Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz Collecting netCDF4==1.4.2   Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl Collecting wrf-python==1.3.2   ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl   ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=ElqsY7uvl7hzUpr%2BxZ%2B3XlIl%2BN0LcVed3o%2BriVtwdVI%3D&st=2019-12-21T16%3A18%3A44Z&se=2019-12-21T16%3A24%3A44Z&sp=r ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=ElqsY7uvl7hzUpr%2BxZ%2B3XlIl%2BN0LcVed3o%2BriVtwdVI%3D&st=2019-12-21T16%3A18%3A44Z&se=2019-12-21T16%3A24%3A44Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl 
Traceback (most recent call last):
  File "C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['C:\\Program Files\\QGIS 3.4\\bin\\python-qgis-ltr.bat', '-m', 'pip', 'install', '--prefix', 'C:\\Users\\bnkre\\AppData\\Local\\gis4wrf\\python37', 'f90nml==1.0.2', 'netCDF4==1.4.2', 'https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added C:\Users\bnkre\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\bnkre\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\bnkre\AppData\Local\gis4wrf\python37C:\Program Files\QGIS 3.4\bin\python-qgis-ltr.bat -m pip install --prefix C:\Users\bnkre\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2
  Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz
Collecting netCDF4==1.4.2
  Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl
Collecting wrf-python==1.3.2
  ERROR: HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl
  ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=ElqsY7uvl7hzUpr%2BxZ%2B3XlIl%2BN0LcVed3o%2BriVtwdVI%3D&st=2019-12-21T16%3A18%3A44Z&se=2019-12-21T16%3A24%3A44Z&sp=r
ERROR: Could not install requirement wrf-python==1.3.2 from https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidatav2.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-32/472wbd8dnd3exv2w/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=ElqsY7uvl7hzUpr%2BxZ%2B3XlIl%2BN0LcVed3o%2BriVtwdVI%3D&st=2019-12-21T16%3A18%3A44Z&se=2019-12-21T16%3A24%3A44Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/472wbd8dnd3exv2w/artifacts/wrf_python-1.3.2-cp37-cp37m-win_amd64.whl



Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.14-Madeira Madeira, c92881c294 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.4\apps\gdal2\pymod3\lib\site-packages
C:\Users\bnkre\Documents
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/bnkre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\bnkre\AppData\Local\gis4wrf\python37
C:\Users\bnkre\AppData\Local\gis4wrf\python37\lib\site-packages

**Comment by letmaik** [comment]
This is an issue on Windows only and we'll release a hotfix as soon as possible. Unfortunately there's no work-around available for this and until the hotfix is released, gis4wrf cannot be installed on Windows currently.
