### ISSUE TITLE
RUN wrf error: Program received signal 11 (SIGSEGV): Segmentation fault

### ISSUE THREAD

**Issue by hoangnghiem72** [GIS4WRF/gis4wrf#168]
**Describe the bug**
There is an error with RUN wrf when I try to apply GIS4WRF for 3 day simulation running.

**To Reproduce**
1. Go to 'Run'
2. Click on 'Run WRF.'
3. See error as show in attach file.

**Screenshots** in attached file

**System Information:**
 - OS: [Fedora 31]
 - QGIS: [3.12]
[RUN_wrf.log_gis4wrf.txt](https://github.com/GIS4WRF/gis4wrf/files/4471352/RUN_wrf.log_gis4wrf.txt)
![Screenshot from 2020-04-14 02-05-11](https://user-images.githubusercontent.com/63412472/79151778-436e8f00-7df5-11ea-90a1-5ec179218908.png)

Please help me to correct the error.

**Comment by dmey** [comment]
From your log it looks like you have exceeded the Courant–Friedrichs–Lewy (CFL) condition probably due to the choice of time step. See `points exceeded cfl=2` around line 13961. This is not really anything to do with GIS4WRF, but rather with the science/choice of configuration parameters. I would suggest to double check the configuration or ask the community on the [WRF support forum](https://forum.mmm.ucar.edu/phpBB3/). I will close this issue now.

PS. As a side note, I noticed that you are using the serial version of the prebuilt binaries. If you have more than one core on your machine, try with the [mpi version](https://gis4wrf.github.io/configuration/#integration-with-wpswrf) -- it may save you time in the long run...
