### ISSUE TITLE
Namelist.input parser ignores run_* parameters 

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#40]
The following `namelist.input` parameters do not appear as a namelist option and cannot be added manually as they are ignored. 

```
run_days
run time in days
Type: int
Example: 0

run_hours
run time in hours *note: if it is more than 1 day, you may use both run_days and run_hours or just run_hours. e.g. if the total run length is 36 hrs, you may set run_days = 1, and run_hours = 12, or run_days = 0, and run_hours = 36
Type: int
Example: 0

run_minutes
run time in minutes
Type: int
Example: 0

run_seconds
run time in seconds
Type: int
Example: 0
```

**Comment by letmaik** [comment]
This is by design currently (although I agree it is slightly confusing). real.exe only uses start and end times, whereas wrf uses start times and can use either end times or run durations. Is there any semantic difference I'm not aware of in adjusting run_* vs end_* in wrf? If there is no difference then it works as intended, such that end_* is used so that it works with real as well.

**Comment by dmey** [comment]
That's correct for real however the run_* option is important to shorten the simulation period when running WRF. The end_* option must be set to at lest the 1 interval period from the met input data to create the boundary conditions, however the user may only want to run a simulation for a few hours. E.g. using input met data with interval=6 hours, the user need to run WRF for at least 6 hours; if the user want to run it for 4 hours they can set the run_hours=4.
