### ISSUE TITLE
Offer clear geo dataset groups  

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#56]
**Is your feature request related to a problem? Please describe.**
In geographical data, it is not clear which DataSet groups contain all essential data for running geogrid. 
**Describe the solution you'd like**
Only specify datasets (e.g. lowres, default) that contain geographical data to run geogrid

**Comment by letmaik** [comment]
Just to clarify, are you referring to downloading of geographic data (in Datasets -> Geo) or selecting geographic datasets (in Simulation -> Data)?

**Comment by hugohartmann** [comment]
selecting geographic datasets (in Simulation -> Data)

**Comment by hugohartmann** [comment]
I understand your point. However, newbies will probably not have knowledge about the GEOGRID.TBL file. Maybe a little bit more documentation is needed on the usage of the geographical datasets. The lowres and high res groups offer a complete dataset that is required for geogrid to run. Could you add more documentation on how to use other geographical datasets? For instance, the n1cd2011_9s dataset, I am not familiar with this one. Is this a complete dataset to run geogrid, or should I add it on top of the complete 'default' group?

**Comment by dmey** [comment]
OK -- I will add it to #87 so that it can be added to the docs. I have also added it to #88 so that it can be mentioned in a tutorial. `n1cd2011_9s` is for CONUS area and `LANDUSEF`  only. If specified before other detasets, it will have precedence over other datasets when Geogrid interpolates data to grid -- e.g. `nlcd2011_9s + lowres` will results in Geogrid picking up `nlcd2011_9s` where available (in this case CONUS). If you think it would be clear enough to address this in docs and tutorial, feel free to close this issue.

**Comment by hugohartmann** [comment]
Fine!
