### ISSUE TITLE
The contours in the graph do not change when moving the time slider

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#63]
**Describe the bug**
When changing the colors in "Symbology" to "Paletted/unique values" and a color ramp (e.g viridis), the colors don't change when moving the time slider. To me it seems a bug, but it could also be related to my basic experience with QGIS ;)

**Operating System Information (please complete the following information):**
 Windows 10

**Comment by letmaik** [comment]
Definitely a bug, it's related to how we interact with QGIS layers and this scenario is just something we haven't considered yet. Unfortunately these things don't just work out of the box since QGIS doesn't know the concept of time or in general data dimensions that are not just "color channels". So we have to code that up manually, but it shouldn't be hard to do in this case.

**Comment by letmaik** [comment]
I just figured out how to do this, and the good thing is it doesn't require code changes.

Instead of "Paletted/unique values", just use "Singleband pseudocolor", then everything works. Paletted is more for cases like land cover which has categories.

**Comment by hugohartmann** [comment]
@letmaik Great! Thanks for pointing me to this solution :) @dmey suggested in an email conversation to work out a visualization tutorial. I can assist here, if needed. I would further discuss this with him/
